### ISSUE TITLE
Optimize node installation, use nvm multi-version tools

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/role_nodejs#1]
Add following functions:
1. install nvm
2. nvm install node-version
3. test node cli, e.g  `node -v`
4. yarn integrate node special version?

**Comment by qiaofeng1227** [comment]
Done

**Comment by chendelin1982** [comment]
environment variable file save  to `/etc/init.d` , it maybe take efficient for Systemd

**Comment by qiaofeng1227** [comment]
Done
