### ISSUE TITLE
node, npm command can not used in the Systemd service directly

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/role_nodejs#5]
`node, npm` command can not used in the Systemd servicen directly, but it can used like this:
```
ExecStart=/bin/bash -c 'source /opt/nvm/nvm.sh;/usr/local/bin/bench start'
```

**Comment by qiaofeng1227** [comment]
You should source nvm.sh in the Process 1 (before application's systemd service)

**Comment by chendelin1982** [comment]
refer to: https://github.com/Websoft9/role_nodejs/issues/2
