### ISSUE TITLE
output apps version

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/role_nodejs#7]
e.g  output `Express` version to the file: /data/logs/install_version.txt

**Comment by zengxc-1996** [comment]
ok: [104.43.218.203] => {
    "end_check_versions.stdout_lines": [
        "pm2 version: 4.5.6",
        "express version: 4.16.1",
        "Node.js version is v13.14.0",
        "nginx version: nginx/1.20.0",
        "mysql  Ver 14.14 Distrib 5.7.34, for Linux (x86_64) using  EditLine wrapper",
        "MongoDB shell version v3.6.23",
        "Docker version 20.10.6, build 370c289",
        "phpmyadmin version: \"version\": \"5.1.0\",",
        "adminmongo version: \"version\": \"0.0.23\",",
        "Redis server v=5.0.9 sha=00000000:0 malloc=jemalloc-5.1.0 bits=64 build=6e174a03b0c4c130",
        "System version: CentOS7.9",
        "Image name: nodejszengxc-CentOS7.9"
